name: Validate PR Languages
on:
  pull_request:
    paths:
      - 'README.md'
      - 'src/**'
      - '.github/scripts/**'

# Full permissions needed for sudo + commenting + git diff
permissions:
  contents: write          # Allows checkout + git diff + push (if needed)
  pull-requests: write     # Allows creating PR comments
  actions: write           # Allows workflow to run sudo commands (critical!)

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # Required for git diff between base/head

      - name: Install jq (for JSON handling)
        run: sudo apt-get update -qq && sudo apt-get install -y jq

      - name: Run validation (fast mode)
        id: validation
        run: |
          chmod +x .github/scripts/validate.sh
          .github/scripts/validate.sh --fast
          # Expose results to later steps
          echo "passing=$(jq -r .passing validate/status.json)" >> "$GITHUB_OUTPUT"
          echo "failing=$(jq -c .failing validate/status.json)" >> "$GITHUB_OUTPUT"

      - name: Comment PR with results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const status = JSON.parse(fs.readFileSync('validate/status.json'));

            const summary = [
              `Validated **${status.passing}** language(s)`,
              status.failing.length ? `Failed **${status.failing.length}** language(s)` : ''
            ].filter(Boolean).join('\n');

            const details = status.failing.length
              ? '\n\n### Failed languages\n' + status.failing.map(l => `- **${l}**`).join('\n')
              : '';

            const body = `## Language Validation\n\n${summary}${details}\n\n*Generated by GitHub Actions*`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

      - name: Fail if any language failed
        if: always()
        run: |
          failing=$(jq '.failing | length' validate/status.json)
          if [[ $failing -gt 0 ]]; then
            echo "Validation failed – $failing language(s) did not pass."
            exit 1
          else
            echo "All ${passing:-0} languages passed!"
          fi