name: 🌟 Nightly Full Validation
on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:      # Manual trigger

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 🔧 Setup & Validate All Languages
      run: |
        chmod +x .github/scripts/validate.sh
        .github/scripts/validate.sh
        
    - name: 📊 Deploy Status (Badges Update!)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./validate/
        force_orphan: true