# .github/workflows/nightly-full-validation.yml
name: Nightly Full Validation

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  actions: write

jobs:
  # ==============================================================
  # Python
  # ==============================================================
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          chmod +x .github/scripts/validate.sh
          .github/scripts/validate.sh python
      - uses: actions/upload-pages-artifact@v3
        with:
          path: validate/
          # 🎯 UNIQUE NAME = NO CONFLICT
          name: python-report

  # ==============================================================
  # Node.js
  # ==============================================================
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          chmod +x .github/scripts/validate.sh
          .github/scripts/validate.sh node
      - uses: actions/upload-pages-artifact@v3
        with:
          path: validate/
          # 🎯 UNIQUE NAME = NO CONFLICT
          name: node-report

  # ==============================================================
  # Go
  # ==============================================================
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: |
          chmod +x .github/scripts/validate.sh
          .github/scripts/validate.sh go
      - uses: actions/upload-pages-artifact@v3
        with:
          path: validate/
          name: go-report

  # ==============================================================
  # Rust
  # ==============================================================
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: |
          chmod +x .github/scripts/validate.sh
          .github/scripts/validate.sh rust
      - uses: actions/upload-pages-artifact@v3
        with:
          path: validate/
          name: rust-report

  # ==============================================================
  # 🚀 COMBINE & DEPLOY (The Magic Step)
  # ==============================================================
  deploy:
    if: always()
    needs: [python, node, go, rust]
    runs-on: ubuntu-latest
    steps:
      - name: Download ALL reports
        uses: actions/download-artifact@v4
        with:
          path: all-reports/
          # Downloads ALL artifacts from ALL jobs above

      - name: Merge into single report
        run: |
          mkdir -p validate
          # Copy the LATEST report (any job works - they all write same format)
          cp all-reports/*/*/index.html validate/index.html || true
          echo "Merged report created!"

      - name: Deploy to GitHub Pages 🎉
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./validate
          force_orphan: true